pipeline {
    agent any
    tools {
        nodejs 'node20' 
    }
    stages {
        stage('Install') { 
            steps { 
                sh 'npm install' 
            } 
        }
        stage('Test') { 
            steps {
                sh 'chmod -x node_modules/.bin/jest'
                sh 'npm test' 
            } 
        }
    }
}
