
pipeline {

    agent any

    tools {

        nodejs 'node20'

    }

    stages {

        stage('Install') {

            steps {

                sh 'npm install'

            }

        }

        stage('Test') {

            steps {

                sh 'node node_modules/jest/bin/jest.js'

            }

        }

    }

}

